### ISSUE TITLE
move base build for main indexer

### ISSUE THREAD

**Issue by kwiss** [ArkProjectNFTs/ark-project#60]
we need to move the docker file to the actions folder with the other docker files
we need to use cache cargo registry to build faster:

```yml
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache
```
