### ISSUE TITLE
Use directly cargo lambda in the github actions instead of a docker for future lambda

### ISSUE THREAD

**Issue by kwiss** [ArkProjectNFTs/ark-project#61]
https://www.cargo-lambda.info/guide/automating-deployments.html#step-3-creating-the-release-workflow

```yaml
name: release

on:
  push:
    branches:
      - main # or master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache

      - name: Release lambda
        run: |
          pip install cargo-lambda
          cargo lambda build --release
          cargo lambda deploy <FUNCTION-NAME>
        env:
          AWS_DEFAULT_REGION: <YOUR-REGION>
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

```
